// plugin.cpp : Defines the entry point for the DLL application.
//

#include "stdafx.h"
#include "IPlugin.h"

#include <math.h>
#include <cmath>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>//to use cout


using namespace std;


////////////////////////////////////////////////////////////////////////
// A concrete plugin implementation
////////////////////////////////////////////////////////////////////////

// Photo-Reactor Plugin class

//****************************************************************************
//This code has been generated by the Mediachance photo reactor Code generator.


#define AddParameter(N,S,V,M1,M2,T,D) {strcpy (pParameters[N].m_sLabel,S);pParameters[N].m_dValue = V;pParameters[N].m_dMin = M1;pParameters[N].m_dMax = M2;pParameters[N].m_nType = T;pParameters[N].m_dSpecialValue = D;}

#define GetValue(N) (pParameters[N].m_dValue)
#define GetValueY(N) (pParameters[N].m_dSpecialValue)

#define SetValue(N,V) {pParameters[N].m_dValue = V;}

#define GetBOOLValue(N) ((BOOL)(pParameters[N].m_dValue==pParameters[N].m_dMax))

// if it is not defined, then here it is
//#define RGB(r,g,b) ((COLORREF)(((BYTE)(r)|((WORD)((BYTE)(g))<<8))|(((DWORD)(BYTE)(b))<<16)))

#define PARAM_RADIUS	0
#define PARAM_LAMBDA	1
#define NUMBER_OF_USER_PARAMS 2






#define MIN(a,b) (((a)<(b))?(a):(b))
#define MAX(a,b) (((a)>(b))?(a):(b))


class Plugin1 : public IPlugin	
{
public:

		//Plugin Icon:
	//you can add your own icon by creating 160x100 png file, naming it the same as plugin dll and then placing it in the plugins folder
	//otherwise a generic icon will be use


	//this is the title of the box in workspace. it should be short
	const char* GetTitle () const
	{
		return "Andy's SRR";
	}
	
	// this will appear in the help pane, you can put your credits and short info
	const char* GetDescription () const
	{
		return "Andy's Spacial Range Reduction.  This seperable spacial Edge preserving filter is simular to a bilateral filter, using the color distance between colors to determine an edge.  If the pixel's color distance is larger than Lambda, then the pixel is skipped, otherwise it is summed up and averaged.  Since this filter is seperable it runs fairly fast, however on larger radius, it will slow down.";
	}

	// BASIC PARAMETERS
	// number of inputs 0,1 or 2
	int GetInputNumber ()
	{
		return 1;
	}

	// number of outputs 0 or 1
	int GetOutputNumber ()
	{
		return 1;
	}

	int GetBoxColor ()
	{
		return RGB(44,78,119);
	}

	int GetTextColor ()
	{
		return RGB(165,236,255);
	}

	// width of the box in the workspace
	// valid are between 50 and 100
	int GetBoxWidth ()
	{
		return 80;
	}

	// set the flags
	// see the interface builder
	// ex: nFlag = FLAG_FAST_PROCESS | FLAG_HELPER;

	//FLAG_NONE same as zero	Default, no other flags set
	//FLAG_UPDATE_IMMEDIATELY	It is very fast process that can update immediately. When user turns the sliders on UI the left display will update
	//							Use Update Immediately only for fast and single loop processes, for example Desaturate, Levels.
	//FLAG_HELPER				It is an helper object. Helper objects will remain visible in Devices and they can react to mouse messages. Example: Knob, Monitor, Bridge Pin
	//FLAG_BINDING				Binding object, attach to other objects and can change its binding value. It never goes to Process_Data functions.  Example: Knob, Switch, Slider
	//FLAG_DUMMY				It is only for interface but never process any data. Never goes to Process_Data functions. Example: Text note
	//FLAG_SKIPFINAL			Process data only during designing, doesn't process during final export. Example: Monitor, Vectorscope 
	//FLAG_LONGPROCESS			Process that takes > 1s to finish. Long Process will display the Progress dialog and will prevent user from changing values during the process.
	//FLAG_NEEDSIZEDATA		    Process need to know size of original image, the zoom and what part of image is visible in the preview. When set the plugin will receive SetSizeData
	//FLAG_NEEDMOUSE			Process will receive Mouse respond data from the workplace. This is only if your object is interactive, for example Knob, Slider

	int GetFlags ()
	{
		// it is fast process
		int nFlag = FLAG_LONGPROCESS;
		
		return nFlag;
	}


	// User Interface Build
	// there is maximum 29 Parameters

	int GetUIParameters (UIParameters* pParameters)
	{

		// label, value, min, max, type_of_control, special_value
		// use the UI builder in the software to generate this
		AddParameter( PARAM_RADIUS ,"Radius", 5.0, 1.0, 50.0, TYPE_SLIDER, 0.0);//inital min max/
		AddParameter( PARAM_LAMBDA ,"Lambda", .09, 0.001, 0.5, TYPE_SLIDER, 0.0);//inital min max/

		return NUMBER_OF_USER_PARAMS;
	}



	// Actual processing function for 1 input
	//***************************************************************************************************
	// Both buffers are the same size
	// don't change the IN buffer or things will go bad for other objects in random fashion
	// the pBGRA_out comes already with pre-copied data from pBGRA_in
	// Note: Don't assume the nWidth and nHeight will be every run the same or that it contains the whole image!!!! 
	// This function receives buffer of the actual preview (it can be just a crop of image when zoomed in) and during the final calculation of the full buffer
	// this is where the image processing happens
	virtual void Process_Data (BYTE* pBGRA_out,BYTE* pBGRA_in, int nWidth, int nHeight, UIParameters* pParameters)
	{
		//List of Parameters

		double dLambda = GetValue(PARAM_LAMBDA);// used to grab radius from control
		double dRadius = GetValue(PARAM_RADIUS);


		int size = int(dRadius + dRadius) + 1;// we want an odd sized kernel

		double* temp=new double[nWidth * nHeight * 4]; // this is our tempory buffer to store image blurred horizonally.
		double* inputimage=new double[nWidth * nHeight * 4]; //

		double Rcolordistance;
		double Gcolordistance;
		double Bcolordistance;

		double Rsum;
		double Gsum;
		double Bsum;

		double fcolorspace = 255.0f;

		//place our image in a seperate array in the 0-1 range, where 0 is darkest and 1 is lightest
		for (int x = 0; x < nWidth; x++)
		{
			for (int y = 0; y < nHeight; y++)
			{
					int nIdx = x * 4 + y * 4 * nWidth;
					double red = pBGRA_in[nIdx + CHANNEL_R] / fcolorspace;
					double green = pBGRA_in[nIdx + CHANNEL_G] / fcolorspace;
					double blue = pBGRA_in[nIdx + CHANNEL_B] / fcolorspace;

					inputimage[nIdx + CHANNEL_R] = red;
					inputimage[nIdx + CHANNEL_G] = green;
					inputimage[nIdx + CHANNEL_B] = blue;
			}
		}


		//blurs horizonally
		for(int y=0;y<nHeight;y++)
		{
			for(int x=0;x<nWidth;x++)
			{
				//clear your variables to process the pixel
				Rsum = 0;
				Gsum = 0;
				Bsum = 0;

				double red = 0;//red
				double green = 0;//green
				double blue = 0;//blue

				double redmin = 65535.0f;
				double greenmin = 65535.0f;
				double bluemin = 65535.0f;
				double redmax = 0;
				double greenmax = 0;
				double bluemax = 0;



				//accumulate colors
				for(int i=max(0,x-size);i<=MIN(nWidth-1,x+size);i++)
				{
					// this stays in center of kernel
					double redKernelCenter   = inputimage[(x + y * nWidth) * 4 + CHANNEL_R];
					double greenKernelCenter = inputimage[(x + y * nWidth) * 4 + CHANNEL_G];
					double blueKernelCenter  = inputimage[(x + y * nWidth) * 4 + CHANNEL_B];
					// this stays in center of kernel

					//this slides / moves along the kernel to collect the neighboring pixels
					double redKernelSlider   = inputimage[(i + y * nWidth) * 4 + CHANNEL_R];
					double greenKernelSlider = inputimage[(i + y * nWidth) * 4 + CHANNEL_G];
					double blueKernelSlider  = inputimage[(i + y * nWidth) * 4 + CHANNEL_B];
					//this slides / moves along the kernel to collect the neighboring pixels

					
					if (redKernelSlider < redmin){redmin = redKernelSlider;}
					if (greenKernelSlider < greenmin){greenmin = greenKernelSlider;}
					if (blueKernelSlider < bluemin){bluemin = blueKernelSlider;}
					if (redKernelSlider > redmax){redmax = redKernelSlider;}
					if (greenKernelSlider > greenmax){greenmax = greenKernelSlider;}
					if (blueKernelSlider > bluemax){bluemax = blueKernelSlider;}


					Rcolordistance = abs(redKernelCenter - redKernelSlider);
					Gcolordistance = abs(greenKernelCenter - greenKernelSlider);
					Bcolordistance = abs(blueKernelCenter - blueKernelSlider);

					if (Rcolordistance < dLambda)
					{
						red += redKernelSlider;
						Rsum ++;
					}

					if (Gcolordistance < dLambda)
					{
						green += greenKernelSlider;
						Gsum ++;
					}

					if (Bcolordistance < dLambda)
					{
						blue += blueKernelSlider;
						Bsum ++;
					}

				}//end i

				{//output
					temp[(x + y * nWidth) * 4 + CHANNEL_R] = red / Rsum;
					temp[(x + y * nWidth) * 4 + CHANNEL_G] = green / Gsum;
					temp[(x + y * nWidth) * 4 + CHANNEL_B] = blue / Bsum;

					//pBGRA_out[(x + y * nWidth) * 4 + CHANNEL_R] = CLAMP255((red / Rsum) * fcolorspace);
					//pBGRA_out[(x + y * nWidth) * 4 + CHANNEL_G] = CLAMP255((green / Gsum) * fcolorspace);
					//pBGRA_out[(x + y * nWidth) * 4 + CHANNEL_B] = CLAMP255((blue / Bsum) * fcolorspace);
				}//end output
			}//end X
		}//end Y

		delete [] inputimage;//delete the array

#pragma region			//test for proof that the image is in temp and blurred horizonally
		//uncomment the routine to see horizontal blur, make sure to comment out the routine below
		
		for (int x = 0; x< nWidth; x++)
		{
			for (int y = 0; y< nHeight; y++)
			{
					//int nIdx = x * 4 + y * 4 * nWidth;
				
					//double nR = temp [nIdx + CHANNEL_R];
					//double nG = temp [nIdx + CHANNEL_G];
					//double nB = temp [nIdx + CHANNEL_B];

					//pBGRA_out[nIdx + CHANNEL_R] = CLAMP255(nR * fcolorspace);
					//pBGRA_out[nIdx + CHANNEL_G] = CLAMP255(nG * fcolorspace);
					//pBGRA_out[nIdx + CHANNEL_B] = CLAMP255(nB * fcolorspace);
			}
		}
		

#pragma endregion


#pragma region		//blurs vertically

		for(int x=0;x<nWidth;x++)
		{
			for(int y=0;y<nHeight;y++)
			{
				//clear your variables to process the pixel
				Rsum = 0;
				Gsum = 0;
				Bsum = 0;

				double red = 0;//red
				double green = 0;//green
				double blue = 0;//blue

				double redmin = 65535.0f;
				double greenmin = 65535.0f;
				double bluemin = 65535.0f;
				double redmax = 0;
				double greenmax = 0;
				double bluemax = 0;

				//accumulate colors
				for(int i=max(0,y-size);i<=min(nHeight-1,y+size);i++)
				{
					// this stays in center of kernel
					double redKernelCenter   = temp[(x + y * nWidth) * 4 + CHANNEL_R];
					double greenKernelCenter = temp[(x + y * nWidth) * 4 + CHANNEL_G];
					double blueKernelCenter  = temp[(x + y * nWidth) * 4 + CHANNEL_B];
					// this stays in center of kernel

					// this slides / moves along the kernel to collect the neighboring pixels
					double redKernelSlider   = temp[(x + i * nWidth) * 4 + CHANNEL_R];
					double greenKernelSlider = temp[(x + i * nWidth) * 4 + CHANNEL_G];
					double blueKernelSlider  = temp[(x + i * nWidth) * 4 + CHANNEL_B];
					//this slides / moves along the kernel to collect the neighboring pixels

					if (redKernelSlider < redmin){redmin = redKernelSlider;}
					if (greenKernelSlider < greenmin){greenmin = greenKernelSlider;}
					if (blueKernelSlider < bluemin){bluemin = blueKernelSlider;}
					if (redKernelSlider > redmax){redmax = redKernelSlider;}
					if (greenKernelSlider > greenmax){greenmax = greenKernelSlider;}
					if (blueKernelSlider > bluemax){bluemax = blueKernelSlider;}

					Rcolordistance = abs(redKernelCenter - redKernelSlider);
					Gcolordistance = abs(greenKernelCenter - greenKernelSlider);
					Bcolordistance = abs(blueKernelCenter - blueKernelSlider);

					if (Rcolordistance < dLambda)
					{
						red += redKernelSlider;
						Rsum ++;
					}

					if (Gcolordistance < dLambda)
					{
						green += greenKernelSlider;
						Gsum ++;
					}

					if (Bcolordistance < dLambda)
					{
						blue += blueKernelSlider;
						Bsum ++;
					}
				}//end i


				{//output	
					pBGRA_out[(x + y * nWidth) * 4 + CHANNEL_R] = CLAMP255((red / Rsum) * fcolorspace);
					pBGRA_out[(x + y * nWidth) * 4 + CHANNEL_G] = CLAMP255((green / Gsum) * fcolorspace);
					pBGRA_out[(x + y * nWidth) * 4 + CHANNEL_B] = CLAMP255((blue / Bsum) * fcolorspace);
				}//end output
			}//end Y
		}//end X


#pragma endregion

		delete [] temp;//delete the array
	}



	// actual processing function for 2 inputs
	//********************************************************************************
	// all buffers are the same size
	// don't change the IN buffers or things will go bad
	// the pBGRA_out comes already with copied data from pBGRA_in1
	virtual void Process_Data2 (BYTE* pBGRA_out, BYTE* pBGRA_in1, BYTE* pBGRA_in2, int nWidth, int nHeight, UIParameters* pParameters)
	{

	}


	//*****************Drawing functions for the BOX *********************************
	//how is the drawing handled
	//DRAW_AUTOMATICALLY	the main program will fully take care of this and draw a box, title, socket and thumbnail
	//DRAW_SIMPLE_A			will draw a box, title and sockets and call CustomDraw
	//DRAW_SIMPLE_B			will draw a box and sockets and call CustomDraw
	//DRAW_SOCKETSONLY      will call CustomDraw and then draw sockets on top of it
	
	// highlighting rectangle around is always drawn except for DRAW_SOCKETSONLY

	virtual int GetDrawingType ()
	{

		int nType = DRAW_AUTOMATICALLY;

		return nType;

	}


	// Custom Drawing
	// custom drawing function called when drawing type is different than DRAW_AUTOMATICALLY
	// it is not always in real pixels but scaled depending on where it is drawn
	// the scale could be from 1.0 to > 1.0
	// so you always multiply the position, sizes, font size, line width with the scale
	
	virtual void CustomDraw (HDC hDC, int nX,int nY, int nWidth, int nHeight, float scale, BOOL bIsHighlighted, UIParameters* pParameters)
	{
	}


	//************ Optional Functions *****************************************************************************************
	// those functions are not necessary for normal effect, they are mostly for special effects and objects


	// Called when FLAG_HELPER set. 
	// When UI data changed (user turned knob) this function will be called as soon as user finish channging the data
	// You will get the latest parameters and also which parameter changed
	// Normally for effects you don't have to do anything here because you will get the same parameters in the process function
	// It is only for helper objects that may not go to Process Data 
	BOOL UIParametersChanged (UIParameters* pParameters, int nParameter)
	{
		
		return FALSE;
	}

	// when button is pressed on UI, this function will be called with the parameter and sub button (for multi button line)
	BOOL UIButtonPushed (int nParam, int nSubButton, UIParameters* pParameters)
	{

		return TRUE;
	}


	// Called when FLAG_NEEDSIZEDATA set
	// Called before each calculation (Process_Data)
	// If your process depends on a position on a frame you may need the data to correctly display it because Process_Data receives only a preview crop
	// Most normal effects don't depend on the position in frame so you don't need the data
	// Example: drawing a circle at a certain position requires to know what is displayed in preview or the circle will be at the same size and position regardless of zoom
	
	// Note: Even if you need position but you don't want to mess with the crop data, just ignore it and pretend the Process_Data are always of full image (they are not). 
	// In worst case this affects only preview when using zoom. The full process image always sends the whole data

	// nOriginalW, nOriginalH - the size of the original - full image. If user sets Resize on input - this will be the resized image
	// nPreviewW, nPreviewH   - this is the currently processed preview width/height - it is the same that Process_Data will receive
	//                        - in full process the nPreviewW, nPreviewH is equal nOriginalW, nOriginalH
	// Crop X1,Y1,X2,Y2       - relative coordinates of preview crop rectangle in <0...1>, for full process they are 0,0,1,1 (full rectangle)	
	// dZoom                  - Zoom of the Preview, for full process the dZoom = 1.0
	void SetSizeData(int nOriginalW, int nOriginalH, int nPreviewW, int nPreviewH, double dCropX1, double dCropY1, double dCropX2, double dCropY2, double dZoom)
	{

		// so if you need the position and zoom, this is the place to get it.
		// Note: because of IBM wisdom the internal bitmaps are on PC always upside down, but the coordinates are not


	}


	// ***** Mouse handling on workplace *************************** 
	// only if FLAG_NEEDMOUSE is set
	//****************************************************************
	//this is for special objects that need to receive mouse, like a knob or slider on workplace
	// normally you use this for FLAG_BINDING objects

	// in coordinates relative to top, left corner of the object (0,0)
	virtual BOOL MouseButtonDown (int nX, int nY, int nWidth, int nHeight, UIParameters* pParameters)
	{
		
		// return FALSE if not handled
		// return TRUE if handled
		return FALSE;
	}

	// in coordinates relative to top, left corner of the object (0,0)
	virtual BOOL MouseMove (int nX, int nY, int nWidth, int nHeight, UIParameters* pParameters)
	{
	

		return FALSE;
	}
	
	// in coordinates relative to top, left corner of the object (0,0)
	virtual BOOL MouseButtonUp (int nX, int nY, int nWidth, int nHeight, UIParameters* pParameters)
	{
		
		// Note: if we changed data and need to recalculate the flow we need to return TRUE

		// return FALSE if not handled
		// return TRUE if handled
		
		return TRUE;
	}


};

extern "C"
{
	// Plugin factory function
	__declspec(dllexport) IPlugin* Create_Plugin ()
	{
		//allocate a new object and return it
		return new Plugin1 ();
	}
	
	// Plugin cleanup function
	__declspec(dllexport) void Release_Plugin (IPlugin* p_plugin)
	{
		//we allocated in the factory with new, delete the passed object
		delete p_plugin;
	}
	
}


// this is the name that will appear in the object library
extern "C" __declspec(dllexport) char* GetPluginName()
{
	return "Andy's SRR";	
}


// This MUST be unique string for each plugin so we can save the data

extern "C" __declspec(dllexport) char* GetPluginID()
{
	
	
	return "com.lumafilters.SRR";
	
}


// category of plugin, for now the EFFECT go to top library box, everything else goes to the middle library box
extern "C" __declspec(dllexport) int GetCategory()
{
		
	return CATEGORY_EFFECT;
	
}